name: anagrammatic
description: Generate detailed anagrams with customizable criteria
authors:
  - Tevan Carrell <tevanc14@gmail.com>
version: 0.39.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_xlider: ^2.4.3
  quiver: ">=2.0.0 <3.0.0"
  shared_preferences: ^0.4.3
  url_launcher: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/scowl_word_lists/
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
        - asset: assets/fonts/RobotoCondensed-BoldItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/RobotoCondensed-Light.ttf
        - asset: assets/fonts/RobotoCondensed-LightItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
  uses-material-design: true
