name: anagrammatic
description: Generate detailed anagrams with customizable criteria
authors:
  - Tevan Carrell <tevanc14@gmail.com>
version: 0.43.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  firebase_analytics: ^3.0.1
  firebase_core: ^0.4.0+1
  flutter:
    sdk: flutter
  flutter_xlider: ^2.4.3
  shared_preferences: ^0.4.3
  url_launcher: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/scowl_word_lists/
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
  uses-material-design: true
