name: anagrammatic
description: Generate detailed anagrams with customizable criteria
authors:
  - Tevan Carrell <tevanc14@gmail.com>
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  firebase_analytics: ^5.0.1
  firebase_core: ^0.4.0+9
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  assets:
    - assets/
    - assets/scowl_word_lists/
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
  uses-material-design: true
